name: image_generator
description: A new ImageGenerator
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"

  flutter: ">=1.12.13+hotfix.6"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+4
  
  # firebase_core: ^1.11.0
  # cloud_firestore: ^3.1.6
  # url_launcher: ^5.4.0   
  # firebase_storage: ^10.2.5
 
  provider: ^4.3.2+2
  http: ^0.13.4
  json_annotation: ^4.4.0 
  curved_navigation_bar: ^1.0.1
  google_fonts: ^2.2.0
  tinycolor: ^1.0.3
  division: ^0.8.8
  pub_semver: ^2.1.0
  cupertino_icons: ^0.1.3
  url_launcher_web: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

  build_runner: ^1.10.0
  json_serializable: ^6.1.4

flutter_driver:
  sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/